version: '2'

services:
  frontend:
    environment:
      - KITSPACE_GITEA_URL=${KITSPACE_SCHEME}://gitea.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}
      - KITSPACE_PROCESSOR_URL=${KITSPACE_SCHEME}://processor.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}
      - INDEX_ISR_INTERVAL=${INDEX_ISR_INTERVAL}
      - USER_ISR_INTERVAL=${USER_ISR_INTERVAL}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
    volumes:
      - frontend-next:/app/.next/
      - frontend-public:/app/public/
    depends_on:
      - gitea
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/hosts:/etc/hosts
    command: /bin/sh --verbose -c "yarn install && yarn build && yarn dev"

  gitea:
    environment:
      - ROOT_URL=${KITSPACE_SCHEME}://gitea.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}/
      - USER_UID=1000
      - USER_GID=1000
      - SECRET_KEY=${GITEA_SECRET_KEY}
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    command: /bin/bash --verbose -c "make build && cp gitea /app/gitea/ && /usr/bin/entrypoint"

  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    environment:
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - KITSPACE_DOMAIN=${KITSPACE_DOMAIN}
      - KITSPACE_SCHEME=${KITSPACE_SCHEME}
      - KITSPACE_EXTERNAL_PORT=${KITSPACE_EXTERNAL_PORT}
      - KITSPACE_ROBOTS_TXT=${KITSPACE_ROBOTS_TXT}
    depends_on:
      - frontend
      - gitea
      - processor
    ports:
      - '${KITSPACE_DEV_PORT}:80'
    volumes:
      - frontend-next:/srv/frontend/.next/
      - frontend-public:/srv/frontend/public/

  processor:
    environment:
      - ALLOWED_CORS_DOMAINS=${KITSPACE_SCHEME}://${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}
      - LOG_LEVEL=info
    volumes:
      - gitea-data:/gitea-data
      - processor-data:/data

volumes:
  frontend-next:
  frontend-public:
  gitea-data:
  postgres-data:
  processor-data:
