version: "2"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "1234:3000"
    environment:
      - "KITSPACE_GITEA_URL=${KITSPACE_SCHEME}://gitea.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}"
    depends_on:
      - gitea
    volumes:
      - ./frontend:/app
      - /app/node_modules

  gitea:
    build:
      context: gitea
      dockerfile: Dockerfile
    environment:
      - ROOT_URL=${KITSPACE_SCHEME}://gitea.${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}/
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3333:3000"
      - "2222:22"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  nginx:
    image: "kitspace/nginx-certbot-plugin:latest"
    ports:
      - "${KITSPACE_DEV_PORT}:80"
    volumes:
      - './nginx:/etc/nginx/conf.d'
      - './frontend:/srv/frontend'
    command: /bin/bash --verbose -c "sed -e 's/@KITSPACE_DOMAIN/${KITSPACE_DOMAIN}/g' -e 's/@KITSPACE_URL/${KITSPACE_SCHEME}:\\/\\/${KITSPACE_DOMAIN}${KITSPACE_EXTERNAL_PORT}/g' /etc/nginx/conf.d/kitspace.template > /etc/nginx/conf.d/default.conf && /opt/command"
    depends_on:
      - frontend
      - gitea

