name: Publish Docker image
on:
  release:
    types: [published]
  push:
    branches:
      - master
      - ghcr
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
      -
         name: Login to GitHub Container Registery
         uses: docker/login-action@v1 
         with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - 
        name: Push frontend to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true          
          tags: ghcr.io/kitspace/frontend
  
      - name: Push processor to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./processor
          file: ./processor/Dockerfile
          push: true          
          tags: ghcr.io/kitspace/frontend

